In [1]:
l = [[] for i in range(5)]
type(l)

list

In [1]:
import torch

In [2]:
t = torch.zeros(4)
t

tensor([0., 0., 0., 0.])

In [3]:
t[0]

tensor(0.)

In [4]:
t[0] = 1
t[1] = 2
t[2] = 3
t[3] = 4
t

tensor([1., 2., 3., 4.])

In [6]:
t2 = torch.zeros(4,1)
t2

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [7]:
c1 = t[:,None]
c1

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [8]:
c2 = t[None,:]
c2

tensor([[1., 2., 3., 4.]])