In [9]:
from PIL import Image
import numpy as np
from torchvision import transforms 
import torch

# 원본 (numpy)

In [27]:
rgb_path = "rgb.jpg"
rgb = Image.open(rgb_path)
rgb_np = np.array(rgb)
print(rgb_np.shape)
rgb_np

(1080, 1440, 3)


array([[[209, 194, 171],
        [209, 194, 171],
        [209, 194, 171],
        ...,
        [180, 167, 150],
        [180, 167, 150],
        [180, 167, 150]],

       [[209, 194, 171],
        [209, 194, 171],
        [209, 194, 171],
        ...,
        [180, 167, 150],
        [180, 167, 150],
        [180, 167, 150]],

       [[209, 194, 171],
        [209, 194, 171],
        [209, 194, 171],
        ...,
        [180, 167, 150],
        [180, 167, 150],
        [180, 167, 150]],

       ...,

       [[186, 141,  82],
        [187, 142,  83],
        [187, 142,  83],
        ...,
        [ 22,  29,  45],
        [ 21,  28,  44],
        [ 20,  27,  43]],

       [[187, 142,  83],
        [187, 142,  83],
        [187, 142,  85],
        ...,
        [ 22,  29,  45],
        [ 22,  29,  45],
        [ 22,  29,  45]],

       [[187, 142,  83],
        [187, 142,  83],
        [188, 143,  86],
        ...,
        [ 23,  30,  46],
        [ 23,  30,  46],
        [ 17,  24,  40]]

# MinMax 정규화

In [19]:
rgb_minmax = rgb_np / 255
print(rgb_minmax.shape)
rgb_minmax

(1080, 1440, 3)


array([[[0.81960784, 0.76078431, 0.67058824],
        [0.81960784, 0.76078431, 0.67058824],
        [0.81960784, 0.76078431, 0.67058824],
        ...,
        [0.70588235, 0.65490196, 0.58823529],
        [0.70588235, 0.65490196, 0.58823529],
        [0.70588235, 0.65490196, 0.58823529]],

       [[0.81960784, 0.76078431, 0.67058824],
        [0.81960784, 0.76078431, 0.67058824],
        [0.81960784, 0.76078431, 0.67058824],
        ...,
        [0.70588235, 0.65490196, 0.58823529],
        [0.70588235, 0.65490196, 0.58823529],
        [0.70588235, 0.65490196, 0.58823529]],

       [[0.81960784, 0.76078431, 0.67058824],
        [0.81960784, 0.76078431, 0.67058824],
        [0.81960784, 0.76078431, 0.67058824],
        ...,
        [0.70588235, 0.65490196, 0.58823529],
        [0.70588235, 0.65490196, 0.58823529],
        [0.70588235, 0.65490196, 0.58823529]],

       ...,

       [[0.72941176, 0.55294118, 0.32156863],
        [0.73333333, 0.55686275, 0.3254902 ],
        [0.73333333, 0

# MinMax한 numpy에 ToTensor 수행 그리고 다시 numpy로 변경 (동일한 값 기대함)

In [20]:
transformer = transforms.Compose([transforms.ToTensor()])

# tensor = torch.from_numpy(rgb_minmax)
tensor = transformer(rgb_minmax)
print(tensor.shape)
tensor

torch.Size([3, 1080, 1440])


tensor([[[0.8196, 0.8196, 0.8196,  ..., 0.7059, 0.7059, 0.7059],
         [0.8196, 0.8196, 0.8196,  ..., 0.7059, 0.7059, 0.7059],
         [0.8196, 0.8196, 0.8196,  ..., 0.7059, 0.7059, 0.7059],
         ...,
         [0.7294, 0.7333, 0.7333,  ..., 0.0863, 0.0824, 0.0784],
         [0.7333, 0.7333, 0.7333,  ..., 0.0863, 0.0863, 0.0863],
         [0.7333, 0.7333, 0.7373,  ..., 0.0902, 0.0902, 0.0667]],

        [[0.7608, 0.7608, 0.7608,  ..., 0.6549, 0.6549, 0.6549],
         [0.7608, 0.7608, 0.7608,  ..., 0.6549, 0.6549, 0.6549],
         [0.7608, 0.7608, 0.7608,  ..., 0.6549, 0.6549, 0.6549],
         ...,
         [0.5529, 0.5569, 0.5569,  ..., 0.1137, 0.1098, 0.1059],
         [0.5569, 0.5569, 0.5569,  ..., 0.1137, 0.1137, 0.1137],
         [0.5569, 0.5569, 0.5608,  ..., 0.1176, 0.1176, 0.0941]],

        [[0.6706, 0.6706, 0.6706,  ..., 0.5882, 0.5882, 0.5882],
         [0.6706, 0.6706, 0.6706,  ..., 0.5882, 0.5882, 0.5882],
         [0.6706, 0.6706, 0.6706,  ..., 0.5882, 0.5882, 0.

In [21]:
back_np = tensor.numpy()
print(back_np.shape)
back_np

(3, 1080, 1440)


array([[[0.81960784, 0.81960784, 0.81960784, ..., 0.70588235,
         0.70588235, 0.70588235],
        [0.81960784, 0.81960784, 0.81960784, ..., 0.70588235,
         0.70588235, 0.70588235],
        [0.81960784, 0.81960784, 0.81960784, ..., 0.70588235,
         0.70588235, 0.70588235],
        ...,
        [0.72941176, 0.73333333, 0.73333333, ..., 0.08627451,
         0.08235294, 0.07843137],
        [0.73333333, 0.73333333, 0.73333333, ..., 0.08627451,
         0.08627451, 0.08627451],
        [0.73333333, 0.73333333, 0.7372549 , ..., 0.09019608,
         0.09019608, 0.06666667]],

       [[0.76078431, 0.76078431, 0.76078431, ..., 0.65490196,
         0.65490196, 0.65490196],
        [0.76078431, 0.76078431, 0.76078431, ..., 0.65490196,
         0.65490196, 0.65490196],
        [0.76078431, 0.76078431, 0.76078431, ..., 0.65490196,
         0.65490196, 0.65490196],
        ...,
        [0.55294118, 0.55686275, 0.55686275, ..., 0.11372549,
         0.10980392, 0.10588235],
        [0.5

# 원본(numpy)를 ToTensor해서 변경 (MinMax했던 결과와 동일하길 기대)

In [22]:
transformer = transforms.Compose([transforms.ToTensor()])

# tensor = torch.from_numpy(rgb_minmax)
tensor2 = transformer(rgb_np)
print(tensor2.shape)
tensor2

torch.Size([3, 1080, 1440])


tensor([[[0.8196, 0.8196, 0.8196,  ..., 0.7059, 0.7059, 0.7059],
         [0.8196, 0.8196, 0.8196,  ..., 0.7059, 0.7059, 0.7059],
         [0.8196, 0.8196, 0.8196,  ..., 0.7059, 0.7059, 0.7059],
         ...,
         [0.7294, 0.7333, 0.7333,  ..., 0.0863, 0.0824, 0.0784],
         [0.7333, 0.7333, 0.7333,  ..., 0.0863, 0.0863, 0.0863],
         [0.7333, 0.7333, 0.7373,  ..., 0.0902, 0.0902, 0.0667]],

        [[0.7608, 0.7608, 0.7608,  ..., 0.6549, 0.6549, 0.6549],
         [0.7608, 0.7608, 0.7608,  ..., 0.6549, 0.6549, 0.6549],
         [0.7608, 0.7608, 0.7608,  ..., 0.6549, 0.6549, 0.6549],
         ...,
         [0.5529, 0.5569, 0.5569,  ..., 0.1137, 0.1098, 0.1059],
         [0.5569, 0.5569, 0.5569,  ..., 0.1137, 0.1137, 0.1137],
         [0.5569, 0.5569, 0.5608,  ..., 0.1176, 0.1176, 0.0941]],

        [[0.6706, 0.6706, 0.6706,  ..., 0.5882, 0.5882, 0.5882],
         [0.6706, 0.6706, 0.6706,  ..., 0.5882, 0.5882, 0.5882],
         [0.6706, 0.6706, 0.6706,  ..., 0.5882, 0.5882, 0.