In [8]:
from sklearn.preprocessing import StandardScaler
import numpy as np
from PIL import Image
import torch
from torchvision import transforms 

In [19]:
rgb_array = np.zeros((3,1440,1080))
print(rgb_array.shape)
rgb_array

(3, 1440, 1080)


array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [10]:
rgb_path = "rgb.jpg"
rgb = Image.open(rgb_path).convert("RGB")
print(rgb.size)
rgb_np = np.array(rgb)
print(rgb_np.shape)

(1440, 1080)
(1080, 1440, 3)


In [11]:
swaped_rgb_np = rgb_np.swapaxes(0,2)
print(swaped_rgb_np.shape)

(3, 1440, 1080)


# RGB 1채널

In [12]:
print(swaped_rgb_np[0].shape)
print(f"max: {swaped_rgb_np[0].max()}")
print(f"min: {swaped_rgb_np[0].min()}")
print(swaped_rgb_np[0])

(1440, 1080)
max: 255
min: 0
[[209 209 209 ... 186 187 187]
 [209 209 209 ... 187 187 187]
 [209 209 209 ... 187 187 188]
 ...
 [180 180 180 ...  22  22  23]
 [180 180 180 ...  21  22  23]
 [180 180 180 ...  20  22  17]]


In [13]:
std_result0 = StandardScaler().fit_transform(swaped_rgb_np[0])
rgb_array[0] = std_result0
std_result0

array([[-0.02351833, -0.02695233, -0.02343293, ..., -0.26774635,
        -0.26040074, -0.26885844],
       [-0.02351833, -0.02695233, -0.02343293, ..., -0.25262893,
        -0.26040074, -0.26885844],
       [-0.02351833, -0.02695233, -0.02343293, ..., -0.25262893,
        -0.26040074, -0.25359685],
       ...,
       [-1.33301905, -1.33570735, -1.33166713, ..., -2.74700365,
        -2.76540973, -2.77176013],
       [-1.33301905, -1.33570735, -1.33166713, ..., -2.76212108,
        -2.76540973, -2.77176013],
       [-1.33301905, -1.33570735, -1.33166713, ..., -2.7772385 ,
        -2.76540973, -2.8633297 ]])

# RGB 2채널

In [14]:
print(swaped_rgb_np[1].shape)
print(f"max: {swaped_rgb_np[1].max()}")
print(f"min: {swaped_rgb_np[1].min()}")
print(swaped_rgb_np[1])

(1440, 1080)
max: 255
min: 0
[[194 194 194 ... 141 142 142]
 [194 194 194 ... 142 142 142]
 [194 194 194 ... 142 142 143]
 ...
 [167 167 167 ...  29  29  30]
 [167 167 167 ...  28  29  30]
 [167 167 167 ...  27  29  24]]


In [15]:
std_result1 = StandardScaler().fit_transform(swaped_rgb_np[1])
rgb_array[1] = std_result1
std_result1

array([[-0.07138493, -0.07308619, -0.06978166, ..., -0.66945215,
        -0.6647855 , -0.67400104],
       [-0.07138493, -0.07308619, -0.06978166, ..., -0.65604448,
        -0.6647855 , -0.67400104],
       [-0.07138493, -0.07308619, -0.06978166, ..., -0.65604448,
        -0.6647855 , -0.66049664],
       ...,
       [-1.07880644, -1.07967182, -1.07575528, ..., -2.17111059,
        -2.18467953, -2.18649426],
       [-1.07880644, -1.07967182, -1.07575528, ..., -2.18451826,
        -2.18467953, -2.18649426],
       [-1.07880644, -1.07967182, -1.07575528, ..., -2.19792592,
        -2.18467953, -2.26752068]])

# RGB 3채널

In [16]:
print(swaped_rgb_np[2].shape)
print(f"max: {swaped_rgb_np[2].max()}")
print(f"min: {swaped_rgb_np[2].min()}")
print(swaped_rgb_np[2])

(1440, 1080)
max: 255
min: 0
[[171 171 171 ...  82  83  83]
 [171 171 171 ...  83  83  83]
 [171 171 171 ...  83  85  86]
 ...
 [150 150 150 ...  45  45  46]
 [150 150 150 ...  44  45  46]
 [150 150 150 ...  43  45  40]]


In [17]:
std_result2 = StandardScaler().fit_transform(swaped_rgb_np[2])
rgb_array[2] = std_result2
std_result2

array([[-0.21421727, -0.21710051, -0.21564303, ..., -1.13736351,
        -1.13404334, -1.14313808],
       [-0.21421727, -0.21710051, -0.21564303, ..., -1.12566533,
        -1.13404334, -1.14313808],
       [-0.21421727, -0.21710051, -0.21564303, ..., -1.12566533,
        -1.1106016 , -1.10786738],
       ...,
       [-0.85130719, -0.85387252, -0.85171845, ..., -1.57019611,
        -1.57943653, -1.57814337],
       [-0.85130719, -0.85387252, -0.85171845, ..., -1.58189428,
        -1.57943653, -1.57814337],
       [-0.85130719, -0.85387252, -0.85171845, ..., -1.59359246,
        -1.57943653, -1.64868477]])

# 3개 채널 다시 합쳐서 numpy로 만들기

In [18]:
rgb_array

array([[[-0.02351833, -0.02695233, -0.02343293, ..., -0.26774635,
         -0.26040074, -0.26885844],
        [-0.02351833, -0.02695233, -0.02343293, ..., -0.25262893,
         -0.26040074, -0.26885844],
        [-0.02351833, -0.02695233, -0.02343293, ..., -0.25262893,
         -0.26040074, -0.25359685],
        ...,
        [-1.33301905, -1.33570735, -1.33166713, ..., -2.74700365,
         -2.76540973, -2.77176013],
        [-1.33301905, -1.33570735, -1.33166713, ..., -2.76212108,
         -2.76540973, -2.77176013],
        [-1.33301905, -1.33570735, -1.33166713, ..., -2.7772385 ,
         -2.76540973, -2.8633297 ]],

       [[-0.07138493, -0.07308619, -0.06978166, ..., -0.66945215,
         -0.6647855 , -0.67400104],
        [-0.07138493, -0.07308619, -0.06978166, ..., -0.65604448,
         -0.6647855 , -0.67400104],
        [-0.07138493, -0.07308619, -0.06978166, ..., -0.65604448,
         -0.6647855 , -0.66049664],
        ...,
        [-1.07880644, -1.07967182, -1.07575528, ..., -

In [20]:
shapeback_rgb_np = rgb_array.swapaxes(0,2)
shapeback_rgb_np.shape

(1080, 1440, 3)

# 아래가 왜 안 되는지는 모르겠다 ㅠㅠ 되야되는데 ㅠㅠ 

In [ ]:
print(rgb_np[:][:][0].max())
print(rgb_np[:][:][0].min())
rgb_np[0].shape

In [77]:
rgb_tensor = torch.from_numpy(rgb_np)
rgb_tensor.shape

torch.Size([1080, 1440, 3])

In [78]:
std_result = StandardScaler().fit_transform(rgb_np[:][:][0])
std_result

array([[-0.02351833, -0.07138493, -0.21421727],
       [-0.02351833, -0.07138493, -0.21421727],
       [-0.02351833, -0.07138493, -0.21421727],
       ...,
       [-1.33301905, -1.07880644, -0.85130719],
       [-1.33301905, -1.07880644, -0.85130719],
       [-1.33301905, -1.07880644, -0.85130719]])

# RGB 2채널

In [59]:
print(rgb_np[:][:][1].max())
print(rgb_np[:][:][1].min())
rgb_np[:][:][1]

255
145


array([[209, 194, 171],
       [209, 194, 171],
       [209, 194, 171],
       ...,
       [180, 167, 150],
       [180, 167, 150],
       [180, 167, 150]], dtype=uint8)

In [29]:
std_result = StandardScaler().fit_transform(rgb_np[:][:][0])
std_result

array([[-0.02351833, -0.07138493, -0.21421727],
       [-0.02351833, -0.07138493, -0.21421727],
       [-0.02351833, -0.07138493, -0.21421727],
       ...,
       [-1.33301905, -1.07880644, -0.85130719],
       [-1.33301905, -1.07880644, -0.85130719],
       [-1.33301905, -1.07880644, -0.85130719]])

# RGB 3채널

In [31]:
print(rgb_np[:][:][2].max())
print(rgb_np[:][:][2].min())
rgb_np[:][:][5]

255
145


array([[209, 194, 171],
       [209, 194, 171],
       [209, 194, 171],
       ...,
       [180, 167, 150],
       [180, 167, 150],
       [180, 167, 150]], dtype=uint8)

In [3]:
a = "equal"
b = "equal"
if a == b:
    print("good")

good


In [23]:
a = torch.zeros(1,2)
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '