In [45]:
import numpy as np
from open3d import *

In [46]:
path = "/mnt/nas3/yrkim/liveness_lidar_project/GC_project/LDFAS/1. Indoor/1/bonafide/pc_1.ply"

# cloud = read_point_cloud(path)
# draw_geometries([cloud])

print("Load a ply point cloud, print it, and render it")
# ply_point_cloud = o3d.data.PLYPointCloud()
cloud = o3d.io.read_point_cloud(path)
print(cloud)
print(np.asarray(cloud.points))
# o3d.visualization.draw_geometries([cloud])


Load a ply point cloud, print it, and render it
PointCloud with 49152 points.
[[ 1.6857576 -1.6201947 31.446089 ]
 [ 1.6828185 -1.6210761 31.453117 ]
 [ 1.6872741 -1.620445  31.442335 ]
 ...
 [ 1.7766651 -1.6687493 31.425692 ]
 [ 1.7801087 -1.6691065 31.41949  ]
 [ 1.7784309 -1.669449  31.422478 ]]


-----------------------------

In [48]:
vis = o3d.visualization.Visualizer()
vis.create_window('camera_view', 320, 240, 50, 50, True) # width, height, left, top is_window_visible
vis.add_geometry(cloud)
control = vis.get_view_control()
o3d.visualization.draw_geometries([cloud])

[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.


-----------------------------

In [36]:
print(cloud)

geometry::PointCloud with 49152 points.


In [43]:
pc_array = np.asarray([cloud.points])
print(type(cloud))
print(type(pc_array))
print(pc_array)
print(len(pc_array[0]))

<class 'open3d.open3d.geometry.PointCloud'>
<class 'numpy.ndarray'>
[[[ 3.7124412  -0.37966383 -1.0175008 ]
  [ 3.7213168  -0.3787248  -1.0195369 ]
  [ 3.7525938  -0.3702149  -1.0267969 ]
  ...
  [ 1.0057799  -1.3992425  -0.23381893]
  [ 0.99933845 -1.4015361  -0.23313473]
  [ 1.0100014  -1.3994961  -0.23422964]]]
49152


In [42]:
vis = Visualizer()
vis.create_window('camera_view', 320, 240, 50, 50, True) # width, height, left, top is_window_visible
vis.add_geometry(cloud)
control = vis.get_view_control()
draw_geometries([cloud])

NameError: name 'Visualizer' is not defined

In [43]:
fx = 115
fy = 115

init_param = control.convert_to_pinhole_camera_parameters()
cx = init_param.intrinsic.width / 2 - 0.5
cy = init_param.intrinsic.height / 2 - 0.5
init_param.intrinsic.set_intrinsics(init_param.intrinsic.width, 
    init_param.intrinsic.height, fx, fy, cx, cy)
print(init_param.intrinsic.intrinsic_matrix)

control.convert_from_pinhole_camera_parameters(init_param)
current_param = control.convert_to_pinhole_camera_parameters()
print(current_param.intrinsic.intrinsic_matrix)

NameError: name 'control' is not defined

camera::PinholeCameraParameters class.
Access its data via intrinsic and extrinsic.