In [101]:
import torch.nn as nn
import torch
from Network import rgbdp_v1_twostep_model, Face_Detection_Model

In [102]:
device = torch.device("cuda:0")
model = rgbdp_v1_twostep_model(device)

# model.modules
# model.parameters
# model.named_parameters
# model.children
# model.pt_model
# model.rgb_model
# model.state_dict
# model.train
# model.type

# for name, param in model.named_parameters():
#     print(param)

In [ ]:
# for name, param in model.named_parameters():
#     print(name)
#     if "fc" not in name:
#         nn.init.xavier_uniform_(param)

def initialize_weights(model):
    for m in model.modules():
        nn.init.xavier_uniform_(m.weight.data)
        if m.bias:
            nn.init.xavier_uniform_(m.bias.data)       
              
model.apply(initialize_weights)

In [89]:
for name, param in model.named_parameters():
    print(param)

Parameter containing:
tensor([[[[-1.4702e-02,  1.1818e-02, -1.3388e-02,  ..., -3.5918e-03,
           -6.6558e-02, -3.4763e-02],
          [-3.9049e-02,  2.1314e-02,  7.0858e-03,  ...,  6.2617e-03,
           -1.1651e-02, -1.8927e-02],
          [-1.8519e-02, -2.1930e-02,  1.9805e-02,  ..., -1.1890e-02,
            1.6538e-02,  5.5681e-03],
          ...,
          [-3.3537e-02, -3.0509e-02,  5.6791e-02,  ...,  2.8402e-02,
           -3.7810e-02,  3.3857e-02],
          [-2.7952e-02,  1.1089e-02, -2.5615e-02,  ...,  2.7128e-02,
            2.9366e-02, -3.2489e-03],
          [-1.4848e-02, -2.6199e-03,  3.0784e-02,  ...,  5.3554e-03,
           -2.8556e-02, -2.5817e-02]],

         [[ 1.7157e-02, -2.6028e-02, -1.9910e-02,  ...,  7.0152e-03,
           -1.3290e-02, -4.6259e-02],
          [ 7.0987e-03, -1.1531e-02, -1.0427e-02,  ...,  1.6110e-02,
            1.5463e-03,  8.6384e-03],
          [ 9.0372e-03,  1.3468e-02,  4.6473e-03,  ...,  4.7614e-03,
            3.4914e-02,  1.1282e-02]

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.

Parameter containing:
tensor([[[[ 5.6168e-02,  9.6224e-02, -5.1640e-02],
          [ 2.5894e-02,  3.9466e-02, -2.1924e-02],
          [ 2.2250e-02,  9.3369e-02, -4.7724e-02]],

         [[-7.9190e-03,  2.1226e-02,  5.5632e-02],
          [ 1.4652e-02,  5.8486e-02, -6.0447e-02],
          [-2.8686e-02, -1.4377e-02,  3.3442e-02]],

         [[-4.4302e-02,  4.0641e-02,  4.1905e-02],
          [ 1.8194e-02,  6.6081e-02, -8.4858e-02],
          [ 3.1217e-03,  2.2329e-02,  9.3322e-04]],

         ...,

         [[-2.5679e-02, -1.0187e-01, -1.7377e-02],
          [-3.6539e-02, -3.2975e-02, -2.5453e-02],
          [-3.7116e-03,  2.9903e-02,  4.9057e-02]],

         [[ 5.7620e-02, -3.4517e-02,  4.4466e-02],
          [-1.8479e-02, -5.3803e-02, -4.3038e-02],
          [-1.7432e-02,  7.0062e-02,  8.8350e-02]],

         [[ 2.8989e-02, -1.7965e-02, -4.6544e-02],
          [-9.5570e-02, -7.8781e-02,  1.2132e-02],
          [-4.8690e-02,  8.4397e-03, -1.5871e-02]]],


        [[[ 3.2246e-02,  2.2570

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.

Parameter containing:
tensor([[[[ 0.0320,  0.0300,  0.0177],
          [ 0.0433,  0.0250, -0.1183],
          [ 0.0537, -0.0186,  0.0804]],

         [[ 0.0938,  0.0526, -0.0171],
          [-0.0329,  0.0291, -0.0119],
          [-0.0050, -0.0111,  0.0250]],

         [[ 0.0527,  0.0087, -0.0291],
          [ 0.0419,  0.0282, -0.0144],
          [ 0.0207, -0.0282,  0.0289]],

         ...,

         [[ 0.0131,  0.0032, -0.0016],
          [-0.0018,  0.0076,  0.0318],
          [ 0.0834, -0.0293,  0.0486]],

         [[-0.0425, -0.0558,  0.0831],
          [ 0.0217,  0.0592,  0.0586],
          [ 0.0181, -0.0494, -0.0042]],

         [[ 0.0199, -0.0270,  0.0294],
          [ 0.0239,  0.0203,  0.0104],
          [-0.0349,  0.0194, -0.0127]]],


        [[[-0.0382, -0.0029,  0.0119],
          [ 0.0791,  0.0344,  0.0054],
          [ 0.0569,  0.0293,  0.0505]],

         [[-0.0143, -0.0759,  0.0352],
          [ 0.0309, -0.0343,  0.0495],
          [-0.0790, -0.0117,  0.0230]],

         

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.