In [5]:
import numpy as np

In [19]:
t = np.array([
    [[14, 9],
        [26, 11],
        [26, 5]],
              
    [[8, 9],
        [11, 7],
        [20, 3]],
     
    [[8, 9],
        [11, 6],
        [9, 14]]])
t.shape
    

(3, 3, 2)

In [9]:
t = np.array([
    [[14, 9, 2],
        [26, 11, 23],
        [26, 5, 12]],
              
    [[8, 9, 24],
        [11, 7, 17],
        [20, 3, 21]],
             
    [[8, 9, 7],
        [11, 6, 26],
        [9, 14, 8]]])
t.shape
    

(3, 3, 3)

In [20]:
np.where(t==2)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [21]:
np.where(t==6)

(array([2]), array([1]), array([1]))

In [14]:
np.where(t==9)

(array([0, 1, 2, 2]), array([0, 0, 0, 2]), array([1, 1, 1, 0]))

In [22]:
np.where(t==11)

(array([0, 1, 2]), array([1, 1, 1]), array([1, 0, 0]))